version: '2'
services:
  data:
    image: busybox
    volumes:
      - ./volume:/var/lib/mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes_from:
      - data
    container_name: mysql

  web:
    image: php:7.1-apache
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/var/www/html
    links:
      - mysql
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_NAME: 'test'
      DATABASE_USER: 'test'
      DATABASE_PASSWORD: 'test'
    container_name: web